version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.6.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP_ROOT environment variable and create workspace directory"
          command: mkdir -p /workspace/projects/ishiko/cpp && echo 'export ISHIKO_CPP_ROOT="/workspace/projects/ishiko/cpp"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/ishiko/cpp/time
      - run:
          name: Build
          command: cd /workspace/projects/ishiko/cpp/time/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ BasePlatform"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/base-platform.git && cd base-platform/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Errors"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Memory"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/memory.git && cd memory/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Types"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/types.git && cd types/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Collections"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/collections.git && cd collections/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Text"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/text.git && cd text/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Process"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/process.git && cd process/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ IO"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/io.git && cd io/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ FileSystem"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/filesystem.git && cd filesystem/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ XML"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/xml.git && cd xml/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Diff"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/diff.git && cd diff/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ Configuration"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/configuration.git && cd configuration/build-files/gnumake && make
      - run:
          name: "Install test dependency: Ishiko/C++ TestFramework/Core"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/test-framework.git && cd test-framework/core/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/ishiko/cpp/time/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/ishiko/cpp/time/tests/build-files/gnumake && ./IshikoTimeTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/IshikoTime.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/IshikoTime.xml
          destination: IshikoTime-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/IshikoTime.xml
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
